name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Ubuntu-Bionic-GCC:
    runs-on: ubuntu-18.04
    env:
      IUP_BIONIC_URL: https://master.dl.sourceforge.net/project/iup/3.29/Linux%20Libraries/iup-3.29_Linux415_64_lib.tar.gz
    steps:
    - uses: actions/checkout@v2
    - name: Install Packages
      run: sudo apt-get install -y libpcap-dev
    - name: Before Build
      run: |
        mkdir /tmp/iup
        wget $IUP_BIONIC_URL -O /tmp/iup/iup.tar.gz
        tar -xvf /tmp/iup/iup.tar.gz
        printf '\n' | sudo ./install
        printf '\n' | sudo ./install_dev
        cd $GITHUB_WORKSPACE
    - name: Build
      run: make
  Ubuntu-Focal-GCC:
    runs-on: ubuntu-20.04
    env:
      IUP_FOCAL_URL: https://deac-ams.dl.sourceforge.net/project/iup/3.30/Linux%20Libraries/iup-3.30_Linux54_64_lib.tar.gz
    steps:
    - uses: actions/checkout@v2
    - name: Install Packages
      run: sudo apt-get install -y libpcap-dev
    - name: Before Build
      run: |
        mkdir /tmp/iup
        wget $IUP_FOCAL_URL -O /tmp/iup/iup.tar.gz
        tar -xvf /tmp/iup/iup.tar.gz
        printf '\n' | sudo ./install
        printf '\n' | sudo ./install_dev
        cd $GITHUB_WORKSPACE
    - name: Build
      run: make
  Ubuntu-Focal-CLang:
    runs-on: ubuntu-20.04
    env:
      CC: clang
    steps:
    - uses: actions/checkout@v2
    - name: Install Packages
      run: sudo apt-get install -y libpcap-dev
    - name: Build
      run: make bsniffhub
