name: Bsniffhub CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Windows-Latest:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Packages
      run: echo $GITHUB_WORKSPACE
